# Generated by Django 5.2 on 2025-10-15 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeartBeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('ver', models.CharField(default='', max_length=255, null=True)),
            ],
            options={
                'db_table': 'heartbeat',
                'ordering': ['-modified_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255, verbose_name='客户端ID')),
                ('cpu', models.TextField(verbose_name='CPU信息')),
                ('hostname', models.CharField(max_length=255, verbose_name='主机名')),
                ('memory', models.CharField(max_length=50, verbose_name='内存')),
                ('os', models.TextField(verbose_name='操作系统')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('uuid', models.CharField(unique=True, verbose_name='设备UUID')),
                ('version', models.CharField(max_length=50, verbose_name='客户端版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '系统信息',
                'verbose_name_plural': '系统信息',
                'db_table': 'system_info',
                'ordering': ['-created_at'],
            },
        ),
    ]
