# Generated by Django 5.2.7 on 2025-10-31 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('db', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heartbeat',
            options={'ordering': ['-modified_at'], 'verbose_name': '心跳测试', 'verbose_name_plural': '心跳测试'},
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'ordering': ['-created_at'], 'verbose_name': '地址簿', 'verbose_name_plural': '地址簿'},
        ),
        migrations.AlterField(
            model_name='alias',
            name='guid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_guid',
                                    to='db.personal', to_field='guid'),
        ),
        migrations.AlterField(
            model_name='alias',
            name='peer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_peer_id',
                                    to='db.systeminfo', to_field='client_id'),
        ),
        migrations.AlterField(
            model_name='autidconnlog',
            name='type',
            field=models.IntegerField(default=0, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='autidconnlog',
            name='username',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='发起连接的用户'),
        ),
        migrations.AlterField(
            model_name='heartbeat',
            name='client_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='客户端ID'),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='client_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='客户端ID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(max_length=255, verbose_name='标签名称'),
        ),
        migrations.AlterUniqueTogether(
            name='alias',
            unique_together={('alias', 'peer_id', 'guid')},
        ),
        migrations.AlterUniqueTogether(
            name='clienttags',
            unique_together={('peer_id', 'tags', 'guid')},
        ),
        migrations.AlterUniqueTogether(
            name='sharepersonal',
            unique_together={('guid', 'to_share_id')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('tag', 'guid')},
        ),
    ]
