# Generated by Django 5.1.2 on 2025-10-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartbeat',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='systeminfo',
            name='uuid',
            field=models.CharField(max_length=255, unique=True, verbose_name='设备UUID'),
        ),
    ]
