# Generated by Django 5.2.7 on 2025-11-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='client_type',
            field=models.CharField(choices=[(1, 'web'), (2, 'desktop'), (3, 'mobile')], default=2, max_length=255,
                                   verbose_name='客户端类型'),
        ),
        migrations.AlterField(
            model_name='token',
            name='uuid',
            field=models.CharField(max_length=255, null=True, verbose_name='设备UUID'),
        ),
    ]
