# Generated by Django 5.2.7 on 2025-11-03 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='heartbeat',
            old_name='client_id',
            new_name='peer_id',
        ),
        migrations.RenameField(
            model_name='loginclient',
            old_name='client_id',
            new_name='peer_id',
        ),
        migrations.AlterUniqueTogether(
            name='heartbeat',
            unique_together={('uuid', 'peer_id')},
        ),
        migrations.CreateModel(
            name='PeerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_id', models.CharField(max_length=255, unique=True, verbose_name='客户端ID')),
                ('cpu', models.TextField(verbose_name='CPU信息')),
                ('device_name', models.CharField(max_length=255, verbose_name='主机名')),
                ('memory', models.CharField(max_length=50, verbose_name='内存')),
                ('os', models.TextField(verbose_name='操作系统')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('uuid', models.CharField(max_length=255, unique=True, verbose_name='设备UUID')),
                ('version', models.CharField(max_length=50, verbose_name='客户端版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '客户端上报的客户端信息',
                'verbose_name_plural': '客户端上报的客户端信息',
                'db_table': 'peer_info',
                'ordering': ['-created_at'],
                'unique_together': {('uuid', 'peer_id')},
            },
        ),
        migrations.AlterField(
            model_name='alias',
            name='peer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_peer_id',
                                    to='db.peerinfo', to_field='peer_id'),
        ),
        migrations.AlterField(
            model_name='auditfilelog',
            name='controlled_uuid',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='auditfile_controlled', to='db.peerinfo', to_field='uuid',
                                    verbose_name='被控端UUID'),
        ),
        migrations.AlterField(
            model_name='auditfilelog',
            name='controller_uuid',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='auditfile_controller', to='db.peerinfo', to_field='uuid',
                                    verbose_name='控制端UUID'),
        ),
        migrations.AlterField(
            model_name='autidconnlog',
            name='controlled_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditlog_controlled',
                                    to='db.peerinfo', to_field='uuid', verbose_name='被控端UUID'),
        ),
        migrations.AlterField(
            model_name='autidconnlog',
            name='controller_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='auditlog_controller', to='db.peerinfo', to_field='uuid',
                                    verbose_name='控制端UUID'),
        ),
        migrations.AlterField(
            model_name='log',
            name='uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.peerinfo', to_field='uuid',
                                    verbose_name='设备UUID'),
        ),
        migrations.AlterField(
            model_name='peerpersonal',
            name='peer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_personal',
                                    to='db.peerinfo'),
        ),
        migrations.AlterField(
            model_name='usertosystem',
            name='uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.peerinfo', to_field='uuid',
                                    verbose_name='设备UUID'),
        ),
        migrations.DeleteModel(
            name='SystemInfo',
        ),
    ]
