# Generated by Django 5.2.7 on 2025-11-04 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToSystem',
        ),
    ]
