# Generated by Django 5.2 on 2025-10-21 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autidconnlog',
            name='controller_uuid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='auditlog_controller', to='db.systeminfo', to_field='uuid',
                                    verbose_name='控制端UUID'),
        ),
        migrations.AlterField(
            model_name='autidconnlog',
            name='session_id',
            field=models.CharField(max_length=50, null=True, verbose_name='会话ID'),
        ),
    ]
