# Generated by Django 5.2.7 on 2025-11-05 03:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('db', '0002_alter_tag_id_alter_personal_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserToSystem',
        ),
    ]
