# Generated by Django 5.1.2 on 2025-10-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_heartbeat_timestamp_alter_systeminfo_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heartbeat',
            name='modified_at',
            field=models.DateTimeField(),
        ),
    ]
