# Generated by Django 5.1.2 on 2025-10-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_alter_heartbeat_modified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('client_id', models.CharField(max_length=255, verbose_name='客户端ID')),
                ('uuid', models.CharField(max_length=255, verbose_name='设备UUID')),
                ('auto_login', models.BooleanField(default=False, verbose_name='自动登录')),
                ('login_type', models.CharField(max_length=50, verbose_name='登录类型')),
                ('os', models.CharField(max_length=50, verbose_name='操作系统')),
                ('device_type', models.CharField(max_length=50, verbose_name='设备类型')),
                ('device_name', models.CharField(max_length=255, verbose_name='设备名称')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'db_table': 'login_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
