# Generated by Django 5.2 on 2025-10-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0004_loginlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('uuid', models.CharField(max_length=255, verbose_name='设备UUID')),
                ('token', models.CharField(max_length=255, verbose_name='令牌')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_used_at', models.DateTimeField(auto_now=True, verbose_name='最后使用时间')),
            ],
            options={
                'verbose_name': '令牌',
                'verbose_name_plural': '令牌',
                'db_table': 'token',
                'ordering': ['-created_at'],
            },
        ),
    ]
